version: '3'
services:
  postgres:
    image:
      "postgres"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "0.0.0.0:5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-password}
      POSTGRES_USER: ${POSTGRES_USER-user}
      POSTGRES_DB: ${POSTGRES_USER-quizz_db}


volumes:
  postgres-data: