# Generated by Django 4.1.3 on 2022-12-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='login_color',
            field=models.CharField(default='black', max_length=10, verbose_name='Цвет рамки'),
        ),
    ]
