# Generated by Django 4.1.3 on 2022-12-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0002_choice_votes_alter_choice_name'),
        ('users', '0002_customuser_login_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='completed_polls',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='quizz.poll', verbose_name='Пройденный опросы'),
        ),
    ]
